//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCon
    {
        public string MaNV { get; set; }
        public string MaLuong { get; set; }
        public string SoNgayNghi { get; set; }
        public string SoNgayTangCa { get; set; }
        public string TamUng { get; set; }
        public string ViPham { get; set; }
        public string Thuong { get; set; }
    
        public virtual LuongNV LuongNV { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
