//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SoDienThoai { get; set; }
        public string MaChucVu { get; set; }
        public string MaBoPhan { get; set; }
        public string MaGiaiDoan { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgayNhanViec { get; set; }
        public string DanToc { get; set; }
        public string QuocTich { get; set; }
        public string TonGiao { get; set; }
    
        public virtual BoPhan BoPhan { get; set; }
        public virtual ChamCon ChamCon { get; set; }
        public virtual ChamCong ChamCong { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        public virtual GiaiDoan GiaiDoan { get; set; }
    }
}
